import {
  hospital_1,
  hospital_2,
  hospital_3,
} from "../../../../../public/assets";

export const hostpital_list = [
  {
    id: "123abc",
    image: hospital_1,
    name: "Riverside General Hospital",
    address: "12, Ola Street, Opposite New Central Road",
    open: true,
    distance: 14.8,
    rating: 4.8,
    number_of_rating: 192,
  },
  {
    id: "124abc",
    image: hospital_2,
    name: "St. Mary's Medical Center",
    address: "45, Green Park Avenue, Near City Mall",
    open: false,
    distance: 8.3,
    rating: 4.5,
    number_of_rating: 250,
  },
  {
    id: "122abc",
    image: hospital_3,
    name: "Green Valley Health and Wellness Hospital",
    address: "23, Mountain View Road, Close to Riverside Park",
    open: true,
    distance: 5.6,
    rating: 4.9,
    number_of_rating: 315,
  },
  {
    id: "395abc",
    image: hospital_1,
    name: "North Shore Regional Medical Facility",
    address: "98, Harbor Street, Adjacent to North Shore Beach",
    open: true,
    distance: 12.1,
    rating: 4.7,
    number_of_rating: 210,
  },
  {
    id: "482abc",
    image: hospital_3,
    name: "Maplewood Community Hospital",
    address: "77, Maplewood Drive, Opposite Maplewood Park",
    open: false,
    distance: 9.4,
    rating: 4.6,
    number_of_rating: 178,
  },
];
